// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eMovie.Models.Data;

#nullable disable

namespace eMovie.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220530185654_fix")]
    partial class fix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("eMovie.Models.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActorId"), 1L, 1);

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActorId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            ActorId = -1,
                            Bio = "This is the Bio of the first actor",
                            FullName = "Actor 1",
                            ProfilePicture = "http://dotnethow.net/images/actors/actor-1.jpeg"
                        },
                        new
                        {
                            ActorId = -2,
                            Bio = "This is the Bio of the second actor",
                            FullName = "Actor 2",
                            ProfilePicture = "http://dotnethow.net/images/actors/actor-2.jpeg"
                        },
                        new
                        {
                            ActorId = -3,
                            Bio = "This is the Bio of the second actor",
                            FullName = "Actor 3",
                            ProfilePicture = "http://dotnethow.net/images/actors/actor-3.jpeg"
                        },
                        new
                        {
                            ActorId = -4,
                            Bio = "This is the Bio of the second actor",
                            FullName = "Actor 4",
                            ProfilePicture = "http://dotnethow.net/images/actors/actor-4.jpeg"
                        },
                        new
                        {
                            ActorId = -5,
                            Bio = "This is the Bio of the second actor",
                            FullName = "Actor 5",
                            ProfilePicture = "http://dotnethow.net/images/actors/actor-5.jpeg"
                        });
                });

            modelBuilder.Entity("eMovie.Models.Actor_Movie", b =>
                {
                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("ActorId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("Actors_Movies");

                    b.HasData(
                        new
                        {
                            ActorId = -1,
                            MovieId = -1
                        },
                        new
                        {
                            ActorId = -3,
                            MovieId = -1
                        },
                        new
                        {
                            ActorId = -1,
                            MovieId = -2
                        },
                        new
                        {
                            ActorId = -4,
                            MovieId = -2
                        },
                        new
                        {
                            ActorId = -1,
                            MovieId = -3
                        },
                        new
                        {
                            ActorId = -2,
                            MovieId = -3
                        },
                        new
                        {
                            ActorId = -5,
                            MovieId = -3
                        },
                        new
                        {
                            ActorId = -2,
                            MovieId = -4
                        },
                        new
                        {
                            ActorId = -3,
                            MovieId = -4
                        },
                        new
                        {
                            ActorId = -4,
                            MovieId = -4
                        },
                        new
                        {
                            ActorId = -2,
                            MovieId = -5
                        },
                        new
                        {
                            ActorId = -3,
                            MovieId = -5
                        },
                        new
                        {
                            ActorId = -4,
                            MovieId = -5
                        },
                        new
                        {
                            ActorId = -5,
                            MovieId = -5
                        },
                        new
                        {
                            ActorId = -3,
                            MovieId = -6
                        },
                        new
                        {
                            ActorId = -4,
                            MovieId = -6
                        },
                        new
                        {
                            ActorId = -5,
                            MovieId = -6
                        });
                });

            modelBuilder.Entity("eMovie.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieCategory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TheaterId")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.HasIndex("ProducerId");

                    b.HasIndex("TheaterId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = -1,
                            Description = "This is the Life movie description",
                            EndDate = new DateTime(2022, 6, 9, 11, 56, 54, 208, DateTimeKind.Local).AddTicks(9278),
                            ImageURL = "http://dotnethow.net/images/movies/movie-3.jpeg",
                            MovieCategory = 3,
                            Name = "Life",
                            Price = 39.5,
                            ProducerId = -3,
                            StartDate = new DateTime(2022, 5, 20, 11, 56, 54, 208, DateTimeKind.Local).AddTicks(9242),
                            TheaterId = -3
                        },
                        new
                        {
                            MovieId = -2,
                            Description = "This is the Shawshank Redemption description",
                            EndDate = new DateTime(2022, 6, 2, 11, 56, 54, 208, DateTimeKind.Local).AddTicks(9283),
                            ImageURL = "http://dotnethow.net/images/movies/movie-1.jpeg",
                            MovieCategory = 5,
                            Name = "The Shawshank Redemption",
                            Price = 29.5,
                            ProducerId = -1,
                            StartDate = new DateTime(2022, 5, 30, 11, 56, 54, 208, DateTimeKind.Local).AddTicks(9281),
                            TheaterId = -1
                        },
                        new
                        {
                            MovieId = -3,
                            Description = "This is the Ghost movie description",
                            EndDate = new DateTime(2022, 6, 6, 11, 56, 54, 208, DateTimeKind.Local).AddTicks(9287),
                            ImageURL = "http://dotnethow.net/images/movies/movie-4.jpeg",
                            MovieCategory = 5,
                            Name = "Ghost",
                            Price = 39.5,
                            ProducerId = -4,
                            StartDate = new DateTime(2022, 5, 30, 11, 56, 54, 208, DateTimeKind.Local).AddTicks(9285),
                            TheaterId = -4
                        },
                        new
                        {
                            MovieId = -4,
                            Description = "This is the Race movie description",
                            EndDate = new DateTime(2022, 5, 25, 11, 56, 54, 208, DateTimeKind.Local).AddTicks(9291),
                            ImageURL = "http://dotnethow.net/images/movies/movie-6.jpeg",
                            MovieCategory = 0,
                            Name = "Race",
                            Price = 39.5,
                            ProducerId = -2,
                            StartDate = new DateTime(2022, 5, 20, 11, 56, 54, 208, DateTimeKind.Local).AddTicks(9289),
                            TheaterId = -1
                        },
                        new
                        {
                            MovieId = -5,
                            Description = "This is the Scoob movie description",
                            EndDate = new DateTime(2022, 5, 28, 11, 56, 54, 208, DateTimeKind.Local).AddTicks(9295),
                            ImageURL = "http://dotnethow.net/images/movies/movie-7.jpeg",
                            MovieCategory = 4,
                            Name = "Scoob",
                            Price = 39.5,
                            ProducerId = -3,
                            StartDate = new DateTime(2022, 5, 20, 11, 56, 54, 208, DateTimeKind.Local).AddTicks(9293),
                            TheaterId = -1
                        },
                        new
                        {
                            MovieId = -6,
                            Description = "This is the Cold Soles movie description",
                            EndDate = new DateTime(2022, 6, 19, 11, 56, 54, 208, DateTimeKind.Local).AddTicks(9299),
                            ImageURL = "http://dotnethow.net/images/movies/movie-8.jpeg",
                            MovieCategory = 2,
                            Name = "Cold Soles",
                            Price = 39.5,
                            ProducerId = -5,
                            StartDate = new DateTime(2022, 6, 2, 11, 56, 54, 208, DateTimeKind.Local).AddTicks(9297),
                            TheaterId = -1
                        });
                });

            modelBuilder.Entity("eMovie.Models.Producer", b =>
                {
                    b.Property<int>("ProducerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProducerId"), 1L, 1);

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProducerId");

                    b.ToTable("Producers");

                    b.HasData(
                        new
                        {
                            ProducerId = -1,
                            Bio = "This is the Bio of the first actor",
                            FullName = "Producer 1",
                            ProfilePictureURL = "http://dotnethow.net/images/producers/producer-1.jpeg"
                        },
                        new
                        {
                            ProducerId = -2,
                            Bio = "This is the Bio of the second actor",
                            FullName = "Producer 2",
                            ProfilePictureURL = "http://dotnethow.net/images/producers/producer-2.jpeg"
                        },
                        new
                        {
                            ProducerId = -3,
                            Bio = "This is the Bio of the second actor",
                            FullName = "Producer 3",
                            ProfilePictureURL = "http://dotnethow.net/images/producers/producer-3.jpeg"
                        },
                        new
                        {
                            ProducerId = -4,
                            Bio = "This is the Bio of the second actor",
                            FullName = "Producer 4",
                            ProfilePictureURL = "http://dotnethow.net/images/producers/producer-4.jpeg"
                        },
                        new
                        {
                            ProducerId = -5,
                            Bio = "This is the Bio of the second actor",
                            FullName = "Producer 5",
                            ProfilePictureURL = "http://dotnethow.net/images/producers/producer-5.jpeg"
                        });
                });

            modelBuilder.Entity("eMovie.Models.Theaters", b =>
                {
                    b.Property<int>("TheaterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TheaterId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TheaterId");

                    b.ToTable("Theaters");

                    b.HasData(
                        new
                        {
                            TheaterId = -1,
                            Description = "This is the description of the first cinema",
                            Logo = "http://dotnethow.net/images/cinemas/cinema-1.jpeg",
                            Name = "Theater 1"
                        },
                        new
                        {
                            TheaterId = -2,
                            Description = "This is the description of the first cinema",
                            Logo = "http://dotnethow.net/images/cinemas/cinema-2.jpeg",
                            Name = "Theater 2"
                        },
                        new
                        {
                            TheaterId = -3,
                            Description = "This is the description of the first cinema",
                            Logo = "http://dotnethow.net/images/cinemas/cinema-3.jpeg",
                            Name = "Theater 3"
                        },
                        new
                        {
                            TheaterId = -4,
                            Description = "This is the description of the first cinema",
                            Logo = "http://dotnethow.net/images/cinemas/cinema-4.jpeg",
                            Name = "Theater 4"
                        },
                        new
                        {
                            TheaterId = -5,
                            Description = "This is the description of the first cinema",
                            Logo = "http://dotnethow.net/images/cinemas/cinema-5.jpeg",
                            Name = "Theaters 5"
                        });
                });

            modelBuilder.Entity("eMovie.Models.Actor_Movie", b =>
                {
                    b.HasOne("eMovie.Models.Actor", "Actor")
                        .WithMany("Actors_Movies")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eMovie.Models.Movie", "Movie")
                        .WithMany("Actors_Movies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("eMovie.Models.Movie", b =>
                {
                    b.HasOne("eMovie.Models.Producer", "Producer")
                        .WithMany("Movies")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eMovie.Models.Theaters", "Theaters")
                        .WithMany("Movies")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producer");

                    b.Navigation("Theaters");
                });

            modelBuilder.Entity("eMovie.Models.Actor", b =>
                {
                    b.Navigation("Actors_Movies");
                });

            modelBuilder.Entity("eMovie.Models.Movie", b =>
                {
                    b.Navigation("Actors_Movies");
                });

            modelBuilder.Entity("eMovie.Models.Producer", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("eMovie.Models.Theaters", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
